# Generated by Django 4.2.4 on 2023-08-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=100)),
                ('res_description', models.TextField()),
                ('res_image', models.ImageField(upload_to='res')),
            ],
        ),
    ]
